# Generated by Django 5.2.4 on 2025-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tickettype_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total maximum capacity for this event'),
        ),
    ]
