# Generated by Django 5.2.4 on 2025-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
